INCLUDE_UTIL_PATH=../../util
INCLUDE_NSPR_PATH=../../../../dist/Linux4.15_x86_64_cc_glibc_PTH_64_DBG.OBJ/include/

INCLUDE_PATHS=-I$(INCLUDE_UTIL_PATH) -I$(INCLUDE_NSPR_PATH)

mpi.o:mpi.c
	gcc $(INCLUDE_PATHS) -c mpi.c

